//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ArabicLang.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="ArabicLangParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface IArabicLangVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArabicLangParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] ArabicLangParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArabicLangParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] ArabicLangParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArabicLangParser.definitions_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefinitions_part([NotNull] ArabicLangParser.Definitions_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArabicLangParser.consts_def_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConsts_def_part([NotNull] ArabicLangParser.Consts_def_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArabicLangParser.const_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConst_def([NotNull] ArabicLangParser.Const_defContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArabicLangParser.types_def_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypes_def_part([NotNull] ArabicLangParser.Types_def_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArabicLangParser.type_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_def([NotNull] ArabicLangParser.Type_defContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArabicLangParser.complex_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComplex_type([NotNull] ArabicLangParser.Complex_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArabicLangParser.list_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitList_type([NotNull] ArabicLangParser.List_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArabicLangParser.record_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRecord_type([NotNull] ArabicLangParser.Record_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArabicLangParser.fields_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFields_list([NotNull] ArabicLangParser.Fields_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArabicLangParser.field_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitField_def([NotNull] ArabicLangParser.Field_defContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArabicLangParser.vars_def_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVars_def_part([NotNull] ArabicLangParser.Vars_def_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArabicLangParser.var_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar_def([NotNull] ArabicLangParser.Var_defContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArabicLangParser.vars_group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVars_group([NotNull] ArabicLangParser.Vars_groupContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArabicLangParser.procs_def_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcs_def_part([NotNull] ArabicLangParser.Procs_def_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArabicLangParser.proc_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProc_def([NotNull] ArabicLangParser.Proc_defContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArabicLangParser.proc_header"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProc_header([NotNull] ArabicLangParser.Proc_headerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArabicLangParser.proc_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProc_block([NotNull] ArabicLangParser.Proc_blockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArabicLangParser.formal_params_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFormal_params_list([NotNull] ArabicLangParser.Formal_params_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArabicLangParser.param_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParam_def([NotNull] ArabicLangParser.Param_defContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArabicLangParser.data_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitData_type([NotNull] ArabicLangParser.Data_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArabicLangParser.stmtList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmtList([NotNull] ArabicLangParser.StmtListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArabicLangParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] ArabicLangParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArabicLangParser.conditional_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditional_stmt([NotNull] ArabicLangParser.Conditional_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArabicLangParser.repetition_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRepetition_stmt([NotNull] ArabicLangParser.Repetition_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArabicLangParser.repeat_for_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRepeat_for_stmt([NotNull] ArabicLangParser.Repeat_for_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArabicLangParser.repetition_range"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRepetition_range([NotNull] ArabicLangParser.Repetition_rangeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArabicLangParser.repeat_while_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRepeat_while_stmt([NotNull] ArabicLangParser.Repeat_while_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArabicLangParser.repeat_until_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRepeat_until_stmt([NotNull] ArabicLangParser.Repeat_until_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArabicLangParser.assign_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssign_stmt([NotNull] ArabicLangParser.Assign_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArabicLangParser.input_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInput_stmt([NotNull] ArabicLangParser.Input_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArabicLangParser.output_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOutput_stmt([NotNull] ArabicLangParser.Output_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArabicLangParser.print_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrint_list([NotNull] ArabicLangParser.Print_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArabicLangParser.print_element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrint_element([NotNull] ArabicLangParser.Print_elementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArabicLangParser.call_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCall_stmt([NotNull] ArabicLangParser.Call_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArabicLangParser.actual_params_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActual_params_list([NotNull] ArabicLangParser.Actual_params_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArabicLangParser.actual_param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActual_param([NotNull] ArabicLangParser.Actual_paramContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PowerExpr</c>
	/// labeled alternative in <see cref="ArabicLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPowerExpr([NotNull] ArabicLangParser.PowerExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AddSubOrExpr</c>
	/// labeled alternative in <see cref="ArabicLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAddSubOrExpr([NotNull] ArabicLangParser.AddSubOrExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UnaryPlus</c>
	/// labeled alternative in <see cref="ArabicLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryPlus([NotNull] ArabicLangParser.UnaryPlusContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MultDivModAndExpr</c>
	/// labeled alternative in <see cref="ArabicLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultDivModAndExpr([NotNull] ArabicLangParser.MultDivModAndExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UnaryMinus</c>
	/// labeled alternative in <see cref="ArabicLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryMinus([NotNull] ArabicLangParser.UnaryMinusContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NotExpr</c>
	/// labeled alternative in <see cref="ArabicLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNotExpr([NotNull] ArabicLangParser.NotExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>RelationalExpr</c>
	/// labeled alternative in <see cref="ArabicLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelationalExpr([NotNull] ArabicLangParser.RelationalExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AtomicFactor</c>
	/// labeled alternative in <see cref="ArabicLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtomicFactor([NotNull] ArabicLangParser.AtomicFactorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArabicLangParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFactor([NotNull] ArabicLangParser.FactorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArabicLangParser.var_access"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar_access([NotNull] ArabicLangParser.Var_accessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArabicLangParser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelector([NotNull] ArabicLangParser.SelectorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArabicLangParser.indexed_selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndexed_selector([NotNull] ArabicLangParser.Indexed_selectorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArabicLangParser.field_selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitField_selector([NotNull] ArabicLangParser.Field_selectorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ArabicLangParser.const_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConst_value([NotNull] ArabicLangParser.Const_valueContext context);
}
