//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ArabicLang.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="ArabicLangParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface IArabicLangListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] ArabicLangParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] ArabicLangParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] ArabicLangParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] ArabicLangParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.definitions_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefinitions_part([NotNull] ArabicLangParser.Definitions_partContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.definitions_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefinitions_part([NotNull] ArabicLangParser.Definitions_partContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.consts_def_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConsts_def_part([NotNull] ArabicLangParser.Consts_def_partContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.consts_def_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConsts_def_part([NotNull] ArabicLangParser.Consts_def_partContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.const_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConst_def([NotNull] ArabicLangParser.Const_defContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.const_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConst_def([NotNull] ArabicLangParser.Const_defContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.types_def_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypes_def_part([NotNull] ArabicLangParser.Types_def_partContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.types_def_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypes_def_part([NotNull] ArabicLangParser.Types_def_partContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.type_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType_def([NotNull] ArabicLangParser.Type_defContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.type_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType_def([NotNull] ArabicLangParser.Type_defContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.complex_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComplex_type([NotNull] ArabicLangParser.Complex_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.complex_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComplex_type([NotNull] ArabicLangParser.Complex_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.list_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterList_type([NotNull] ArabicLangParser.List_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.list_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitList_type([NotNull] ArabicLangParser.List_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.record_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRecord_type([NotNull] ArabicLangParser.Record_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.record_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRecord_type([NotNull] ArabicLangParser.Record_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.fields_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFields_list([NotNull] ArabicLangParser.Fields_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.fields_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFields_list([NotNull] ArabicLangParser.Fields_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.field_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterField_def([NotNull] ArabicLangParser.Field_defContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.field_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitField_def([NotNull] ArabicLangParser.Field_defContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.vars_def_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVars_def_part([NotNull] ArabicLangParser.Vars_def_partContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.vars_def_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVars_def_part([NotNull] ArabicLangParser.Vars_def_partContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.var_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVar_def([NotNull] ArabicLangParser.Var_defContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.var_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVar_def([NotNull] ArabicLangParser.Var_defContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.vars_group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVars_group([NotNull] ArabicLangParser.Vars_groupContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.vars_group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVars_group([NotNull] ArabicLangParser.Vars_groupContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.procs_def_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProcs_def_part([NotNull] ArabicLangParser.Procs_def_partContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.procs_def_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProcs_def_part([NotNull] ArabicLangParser.Procs_def_partContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.proc_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProc_def([NotNull] ArabicLangParser.Proc_defContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.proc_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProc_def([NotNull] ArabicLangParser.Proc_defContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.proc_header"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProc_header([NotNull] ArabicLangParser.Proc_headerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.proc_header"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProc_header([NotNull] ArabicLangParser.Proc_headerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.proc_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProc_block([NotNull] ArabicLangParser.Proc_blockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.proc_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProc_block([NotNull] ArabicLangParser.Proc_blockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.formal_params_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFormal_params_list([NotNull] ArabicLangParser.Formal_params_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.formal_params_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFormal_params_list([NotNull] ArabicLangParser.Formal_params_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.param_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParam_def([NotNull] ArabicLangParser.Param_defContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.param_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParam_def([NotNull] ArabicLangParser.Param_defContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.data_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterData_type([NotNull] ArabicLangParser.Data_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.data_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitData_type([NotNull] ArabicLangParser.Data_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.stmtList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStmtList([NotNull] ArabicLangParser.StmtListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.stmtList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStmtList([NotNull] ArabicLangParser.StmtListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] ArabicLangParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] ArabicLangParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.conditional_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConditional_stmt([NotNull] ArabicLangParser.Conditional_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.conditional_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConditional_stmt([NotNull] ArabicLangParser.Conditional_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.repetition_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRepetition_stmt([NotNull] ArabicLangParser.Repetition_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.repetition_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRepetition_stmt([NotNull] ArabicLangParser.Repetition_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.repeat_for_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRepeat_for_stmt([NotNull] ArabicLangParser.Repeat_for_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.repeat_for_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRepeat_for_stmt([NotNull] ArabicLangParser.Repeat_for_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.repetition_range"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRepetition_range([NotNull] ArabicLangParser.Repetition_rangeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.repetition_range"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRepetition_range([NotNull] ArabicLangParser.Repetition_rangeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.repeat_while_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRepeat_while_stmt([NotNull] ArabicLangParser.Repeat_while_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.repeat_while_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRepeat_while_stmt([NotNull] ArabicLangParser.Repeat_while_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.repeat_until_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRepeat_until_stmt([NotNull] ArabicLangParser.Repeat_until_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.repeat_until_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRepeat_until_stmt([NotNull] ArabicLangParser.Repeat_until_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.assign_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssign_stmt([NotNull] ArabicLangParser.Assign_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.assign_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssign_stmt([NotNull] ArabicLangParser.Assign_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.input_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInput_stmt([NotNull] ArabicLangParser.Input_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.input_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInput_stmt([NotNull] ArabicLangParser.Input_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.output_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOutput_stmt([NotNull] ArabicLangParser.Output_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.output_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOutput_stmt([NotNull] ArabicLangParser.Output_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.print_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrint_list([NotNull] ArabicLangParser.Print_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.print_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrint_list([NotNull] ArabicLangParser.Print_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.print_element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrint_element([NotNull] ArabicLangParser.Print_elementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.print_element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrint_element([NotNull] ArabicLangParser.Print_elementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.call_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCall_stmt([NotNull] ArabicLangParser.Call_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.call_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCall_stmt([NotNull] ArabicLangParser.Call_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.actual_params_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterActual_params_list([NotNull] ArabicLangParser.Actual_params_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.actual_params_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitActual_params_list([NotNull] ArabicLangParser.Actual_params_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.actual_param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterActual_param([NotNull] ArabicLangParser.Actual_paramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.actual_param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitActual_param([NotNull] ArabicLangParser.Actual_paramContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>PowerExpr</c>
	/// labeled alternative in <see cref="ArabicLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPowerExpr([NotNull] ArabicLangParser.PowerExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PowerExpr</c>
	/// labeled alternative in <see cref="ArabicLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPowerExpr([NotNull] ArabicLangParser.PowerExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>AddSubOrExpr</c>
	/// labeled alternative in <see cref="ArabicLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddSubOrExpr([NotNull] ArabicLangParser.AddSubOrExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>AddSubOrExpr</c>
	/// labeled alternative in <see cref="ArabicLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddSubOrExpr([NotNull] ArabicLangParser.AddSubOrExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>UnaryPlus</c>
	/// labeled alternative in <see cref="ArabicLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryPlus([NotNull] ArabicLangParser.UnaryPlusContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>UnaryPlus</c>
	/// labeled alternative in <see cref="ArabicLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryPlus([NotNull] ArabicLangParser.UnaryPlusContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>MultDivModAndExpr</c>
	/// labeled alternative in <see cref="ArabicLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultDivModAndExpr([NotNull] ArabicLangParser.MultDivModAndExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>MultDivModAndExpr</c>
	/// labeled alternative in <see cref="ArabicLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultDivModAndExpr([NotNull] ArabicLangParser.MultDivModAndExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>UnaryMinus</c>
	/// labeled alternative in <see cref="ArabicLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryMinus([NotNull] ArabicLangParser.UnaryMinusContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>UnaryMinus</c>
	/// labeled alternative in <see cref="ArabicLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryMinus([NotNull] ArabicLangParser.UnaryMinusContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>NotExpr</c>
	/// labeled alternative in <see cref="ArabicLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNotExpr([NotNull] ArabicLangParser.NotExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NotExpr</c>
	/// labeled alternative in <see cref="ArabicLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNotExpr([NotNull] ArabicLangParser.NotExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>RelationalExpr</c>
	/// labeled alternative in <see cref="ArabicLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelationalExpr([NotNull] ArabicLangParser.RelationalExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>RelationalExpr</c>
	/// labeled alternative in <see cref="ArabicLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelationalExpr([NotNull] ArabicLangParser.RelationalExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>AtomicFactor</c>
	/// labeled alternative in <see cref="ArabicLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtomicFactor([NotNull] ArabicLangParser.AtomicFactorContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>AtomicFactor</c>
	/// labeled alternative in <see cref="ArabicLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtomicFactor([NotNull] ArabicLangParser.AtomicFactorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFactor([NotNull] ArabicLangParser.FactorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFactor([NotNull] ArabicLangParser.FactorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.var_access"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVar_access([NotNull] ArabicLangParser.Var_accessContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.var_access"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVar_access([NotNull] ArabicLangParser.Var_accessContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelector([NotNull] ArabicLangParser.SelectorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelector([NotNull] ArabicLangParser.SelectorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.indexed_selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndexed_selector([NotNull] ArabicLangParser.Indexed_selectorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.indexed_selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndexed_selector([NotNull] ArabicLangParser.Indexed_selectorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.field_selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterField_selector([NotNull] ArabicLangParser.Field_selectorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.field_selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitField_selector([NotNull] ArabicLangParser.Field_selectorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.const_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConst_value([NotNull] ArabicLangParser.Const_valueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.const_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConst_value([NotNull] ArabicLangParser.Const_valueContext context);
}
