//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ArabicLang.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IArabicLangListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class ArabicLangBaseListener : IArabicLangListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] ArabicLangParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] ArabicLangParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] ArabicLangParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] ArabicLangParser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.definitions_part"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefinitions_part([NotNull] ArabicLangParser.Definitions_partContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.definitions_part"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefinitions_part([NotNull] ArabicLangParser.Definitions_partContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.consts_def_part"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConsts_def_part([NotNull] ArabicLangParser.Consts_def_partContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.consts_def_part"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConsts_def_part([NotNull] ArabicLangParser.Consts_def_partContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.const_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConst_def([NotNull] ArabicLangParser.Const_defContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.const_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConst_def([NotNull] ArabicLangParser.Const_defContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.types_def_part"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypes_def_part([NotNull] ArabicLangParser.Types_def_partContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.types_def_part"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypes_def_part([NotNull] ArabicLangParser.Types_def_partContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.type_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType_def([NotNull] ArabicLangParser.Type_defContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.type_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType_def([NotNull] ArabicLangParser.Type_defContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.complex_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComplex_type([NotNull] ArabicLangParser.Complex_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.complex_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComplex_type([NotNull] ArabicLangParser.Complex_typeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.list_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterList_type([NotNull] ArabicLangParser.List_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.list_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitList_type([NotNull] ArabicLangParser.List_typeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.record_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRecord_type([NotNull] ArabicLangParser.Record_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.record_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRecord_type([NotNull] ArabicLangParser.Record_typeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.fields_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFields_list([NotNull] ArabicLangParser.Fields_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.fields_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFields_list([NotNull] ArabicLangParser.Fields_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.field_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterField_def([NotNull] ArabicLangParser.Field_defContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.field_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitField_def([NotNull] ArabicLangParser.Field_defContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.vars_def_part"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVars_def_part([NotNull] ArabicLangParser.Vars_def_partContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.vars_def_part"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVars_def_part([NotNull] ArabicLangParser.Vars_def_partContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.var_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVar_def([NotNull] ArabicLangParser.Var_defContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.var_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVar_def([NotNull] ArabicLangParser.Var_defContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.vars_group"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVars_group([NotNull] ArabicLangParser.Vars_groupContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.vars_group"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVars_group([NotNull] ArabicLangParser.Vars_groupContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.procs_def_part"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProcs_def_part([NotNull] ArabicLangParser.Procs_def_partContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.procs_def_part"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProcs_def_part([NotNull] ArabicLangParser.Procs_def_partContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.proc_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProc_def([NotNull] ArabicLangParser.Proc_defContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.proc_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProc_def([NotNull] ArabicLangParser.Proc_defContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.proc_header"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProc_header([NotNull] ArabicLangParser.Proc_headerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.proc_header"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProc_header([NotNull] ArabicLangParser.Proc_headerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.proc_block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProc_block([NotNull] ArabicLangParser.Proc_blockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.proc_block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProc_block([NotNull] ArabicLangParser.Proc_blockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.formal_params_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFormal_params_list([NotNull] ArabicLangParser.Formal_params_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.formal_params_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFormal_params_list([NotNull] ArabicLangParser.Formal_params_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.param_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParam_def([NotNull] ArabicLangParser.Param_defContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.param_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParam_def([NotNull] ArabicLangParser.Param_defContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.data_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterData_type([NotNull] ArabicLangParser.Data_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.data_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitData_type([NotNull] ArabicLangParser.Data_typeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.stmtList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmtList([NotNull] ArabicLangParser.StmtListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.stmtList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmtList([NotNull] ArabicLangParser.StmtListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] ArabicLangParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] ArabicLangParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.conditional_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditional_stmt([NotNull] ArabicLangParser.Conditional_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.conditional_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditional_stmt([NotNull] ArabicLangParser.Conditional_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.repetition_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRepetition_stmt([NotNull] ArabicLangParser.Repetition_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.repetition_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRepetition_stmt([NotNull] ArabicLangParser.Repetition_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.repeat_for_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRepeat_for_stmt([NotNull] ArabicLangParser.Repeat_for_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.repeat_for_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRepeat_for_stmt([NotNull] ArabicLangParser.Repeat_for_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.repetition_range"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRepetition_range([NotNull] ArabicLangParser.Repetition_rangeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.repetition_range"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRepetition_range([NotNull] ArabicLangParser.Repetition_rangeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.repeat_while_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRepeat_while_stmt([NotNull] ArabicLangParser.Repeat_while_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.repeat_while_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRepeat_while_stmt([NotNull] ArabicLangParser.Repeat_while_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.repeat_until_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRepeat_until_stmt([NotNull] ArabicLangParser.Repeat_until_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.repeat_until_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRepeat_until_stmt([NotNull] ArabicLangParser.Repeat_until_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.assign_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssign_stmt([NotNull] ArabicLangParser.Assign_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.assign_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssign_stmt([NotNull] ArabicLangParser.Assign_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.input_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInput_stmt([NotNull] ArabicLangParser.Input_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.input_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInput_stmt([NotNull] ArabicLangParser.Input_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.output_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOutput_stmt([NotNull] ArabicLangParser.Output_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.output_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOutput_stmt([NotNull] ArabicLangParser.Output_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.print_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrint_list([NotNull] ArabicLangParser.Print_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.print_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrint_list([NotNull] ArabicLangParser.Print_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.print_element"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrint_element([NotNull] ArabicLangParser.Print_elementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.print_element"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrint_element([NotNull] ArabicLangParser.Print_elementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.call_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCall_stmt([NotNull] ArabicLangParser.Call_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.call_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCall_stmt([NotNull] ArabicLangParser.Call_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.actual_params_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterActual_params_list([NotNull] ArabicLangParser.Actual_params_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.actual_params_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitActual_params_list([NotNull] ArabicLangParser.Actual_params_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.actual_param"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterActual_param([NotNull] ArabicLangParser.Actual_paramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.actual_param"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitActual_param([NotNull] ArabicLangParser.Actual_paramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>PowerExpr</c>
	/// labeled alternative in <see cref="ArabicLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPowerExpr([NotNull] ArabicLangParser.PowerExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>PowerExpr</c>
	/// labeled alternative in <see cref="ArabicLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPowerExpr([NotNull] ArabicLangParser.PowerExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>AddSubOrExpr</c>
	/// labeled alternative in <see cref="ArabicLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAddSubOrExpr([NotNull] ArabicLangParser.AddSubOrExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>AddSubOrExpr</c>
	/// labeled alternative in <see cref="ArabicLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAddSubOrExpr([NotNull] ArabicLangParser.AddSubOrExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>UnaryPlus</c>
	/// labeled alternative in <see cref="ArabicLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnaryPlus([NotNull] ArabicLangParser.UnaryPlusContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>UnaryPlus</c>
	/// labeled alternative in <see cref="ArabicLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnaryPlus([NotNull] ArabicLangParser.UnaryPlusContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>MultDivModAndExpr</c>
	/// labeled alternative in <see cref="ArabicLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultDivModAndExpr([NotNull] ArabicLangParser.MultDivModAndExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>MultDivModAndExpr</c>
	/// labeled alternative in <see cref="ArabicLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultDivModAndExpr([NotNull] ArabicLangParser.MultDivModAndExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>UnaryMinus</c>
	/// labeled alternative in <see cref="ArabicLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnaryMinus([NotNull] ArabicLangParser.UnaryMinusContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>UnaryMinus</c>
	/// labeled alternative in <see cref="ArabicLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnaryMinus([NotNull] ArabicLangParser.UnaryMinusContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>NotExpr</c>
	/// labeled alternative in <see cref="ArabicLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNotExpr([NotNull] ArabicLangParser.NotExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>NotExpr</c>
	/// labeled alternative in <see cref="ArabicLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNotExpr([NotNull] ArabicLangParser.NotExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>RelationalExpr</c>
	/// labeled alternative in <see cref="ArabicLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelationalExpr([NotNull] ArabicLangParser.RelationalExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>RelationalExpr</c>
	/// labeled alternative in <see cref="ArabicLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelationalExpr([NotNull] ArabicLangParser.RelationalExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>AtomicFactor</c>
	/// labeled alternative in <see cref="ArabicLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtomicFactor([NotNull] ArabicLangParser.AtomicFactorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>AtomicFactor</c>
	/// labeled alternative in <see cref="ArabicLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtomicFactor([NotNull] ArabicLangParser.AtomicFactorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFactor([NotNull] ArabicLangParser.FactorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFactor([NotNull] ArabicLangParser.FactorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.var_access"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVar_access([NotNull] ArabicLangParser.Var_accessContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.var_access"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVar_access([NotNull] ArabicLangParser.Var_accessContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.selector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelector([NotNull] ArabicLangParser.SelectorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.selector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelector([NotNull] ArabicLangParser.SelectorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.indexed_selector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndexed_selector([NotNull] ArabicLangParser.Indexed_selectorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.indexed_selector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndexed_selector([NotNull] ArabicLangParser.Indexed_selectorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.field_selector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterField_selector([NotNull] ArabicLangParser.Field_selectorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.field_selector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitField_selector([NotNull] ArabicLangParser.Field_selectorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArabicLangParser.const_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConst_value([NotNull] ArabicLangParser.Const_valueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArabicLangParser.const_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConst_value([NotNull] ArabicLangParser.Const_valueContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
