using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace pp
{
    /// <summary>
    /// 🔧 يقوم بتحويل الكود الوسيط إلى كود هدف (Assembly افتراضي)
    /// </summary>
    public class TargetCodeGenerator
    {
        private readonly List<string> _intermediateCode;
        private readonly StringBuilder _targetCode = new StringBuilder();
        private int _labelCounter = 0;

        // 🧠 خريطة لتتبع آخر القيم في المسجلات لتقليل التعليمات الزائدة
        private readonly Dictionary<string, string> _registerMap = new Dictionary<string, string>();

        public TargetCodeGenerator(List<string> intermediateCode)
        {
            _intermediateCode = intermediateCode ?? new List<string>();
        }

        public string Generate()
        {
            _targetCode.Clear();
            _targetCode.AppendLine("; ================================================");
            _targetCode.AppendLine(";        💻 Target Code (Assembly-like)");
            _targetCode.AppendLine(";        Auto-generated by TargetCodeGenerator");
            _targetCode.AppendLine("; ================================================\n");

            foreach (var line in _intermediateCode)
                TranslateInstruction(line.Trim());

            _targetCode.AppendLine("\n; ===== End of Program =====");
            _targetCode.AppendLine("HALT");
            return _targetCode.ToString();
        }

        // ============================================================
        // 🧩 ترجمة تعليمة واحدة من الكود الوسيط إلى كود هدف Assembly
        // ============================================================
        private void TranslateInstruction(string ic)
        {
            if (string.IsNullOrWhiteSpace(ic)) return;

            var parts = ic.Split(new[] { ' ', ',', '(', ')', '\t' }, StringSplitOptions.RemoveEmptyEntries);
            if (parts.Length == 0) return;

            string op = parts[0].ToUpper();

            switch (op)
            {
                // ---------------------------------------
                case "LOAD":
                    EmitLoad(parts[1]);
                    break;

                case "STORE":
                    EmitStore(parts[1]);
                    break;

                case "ADD":
                case "SUB":
                case "MUL":
                case "DIV":
                    EmitArithmetic(op, parts);
                    break;

                case "READ":
                    _targetCode.AppendLine($"    IN {parts[1]}      ; قراءة من المستخدم");
                    break;

                case "WRITE":
                    _targetCode.AppendLine($"    OUT {parts[1]}     ; طباعة على الشاشة");
                    break;

                case "JMP":
                    _targetCode.AppendLine($"    JMP {parts[1]}     ; قفز غير مشروط");
                    break;

                case "JZ":
                    _targetCode.AppendLine($"    CMP R1, 0");
                    _targetCode.AppendLine($"    JZ {parts[1]}      ; قفز إذا كانت القيمة صفر");
                    break;

                case "JNZ":
                    _targetCode.AppendLine($"    CMP R1, 0");
                    _targetCode.AppendLine($"    JNZ {parts[1]}     ; قفز إذا كانت القيمة غير صفر");
                    break;

                case "LABEL":
                    _targetCode.AppendLine($"{parts[1]}:");
                    break;

                case "IFZ":
                    string label = GenerateLabel();
                    _targetCode.AppendLine($"    CMP {parts[1]}, 0");
                    _targetCode.AppendLine($"    JZ {label}          ; شرط: إذا صفر → اذهب إلى {label}");
                    _targetCode.AppendLine($"{label}:");
                    break;

                default:
                    _targetCode.AppendLine($"; ⚠️ لم يتم التعرف على التعليمة: {ic}");
                    break;
            }
        }

        // ============================================================
        // 🧱 دوال مساعدة لتنظيم التوليد
        // ============================================================

        private void EmitLoad(string variable)
        {
            if (_registerMap.ContainsKey("R1") && _registerMap["R1"] == variable)
                _targetCode.AppendLine($"; ⏩ تخطي تحميل {variable} لأنها موجودة بالفعل في R1");
            else
            {
                _targetCode.AppendLine($"    MOV R1, {variable}");
                _registerMap["R1"] = variable;
            }
        }

        private void EmitStore(string variable)
        {
            _targetCode.AppendLine($"    MOV {variable}, R1");
            _registerMap[variable] = "R1";
        }

        private void EmitArithmetic(string op, string[] parts)
        {
            string result = parts.Length > 3 ? parts[3] : null;
            string instruction;
            switch (op)
            {
                case "ADD": instruction = "ADD"; break;
                case "SUB": instruction = "SUB"; break;
                case "MUL": instruction = "MUL"; break;
                case "DIV": instruction = "DIV"; break;
                default: instruction = "NOP"; break;
            }


            _targetCode.AppendLine($"    MOV R1, {parts[1]}");
            _targetCode.AppendLine($"    {instruction} R1, {parts[2]}");
            if (!string.IsNullOrEmpty(result))
                _targetCode.AppendLine($"    MOV {result}, R1");
        }

    private string GenerateLabel()
    {
        _labelCounter++;
        return $"L{_labelCounter}";
    }
}
}
